### PR TITLE
Minor adjustments

### PR DESCRIPTION
**Pull request by matheusmoreira**
`theme_stylesheet_link_tag` now forwards options as described in [this issue](https://github.com/lucasefe/themes_for_rails/issues#issue/12).

Options like `:all`, `:recursive` and `:defaults` depend on `config.stylesheets_dir` and `config.javascripts_dir`, should a wrapper be made around those?

### CODE REVIEW

**Comment by matheusmoreira** [comment]
Done. Updated `dummy_app`, tested it and it apparently works fine.

**Comment by matheusmoreira** [comment]
Lucas?

**Comment by lucasefe** [comment]
Sorry, I have been out for a couple of days. Let me see.

**Comment by lucasefe** [comment]
matheus, I appreciate your effor, but you are using rspec in your last commit, and the project uses test unit. Nevertheless, I have fixed the problem, so a new version is coming soon. If you want, you can use it directly from github to give it a try. Feedback is reaaaaly appreciated. 

gem 'themes_for_rails', :git => 'git://github.com/lucasefe/themes_for_rails.git'

Let me know if it solves the issue.

**Comment by matheusmoreira** [comment]
Great news! I'll adapt my application later and let you know how it works.

Thanks a lot!

**Pull request closed without merging**
